pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK17'
    }

    environment {
        DOCKERHUB_USER = 'rakesh2398'
        BACKEND_IMAGE = "${DOCKERHUB_USER}/chai-kafe-backend:latest"
        FRONTEND_IMAGE = "${DOCKERHUB_USER}/chai-kafe-frontend:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('backend') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        sonar-scanner \
                        -Dsonar.projectKey=chai-kafe-devops \
                        -Dsonar.projectName="Chai Kafe DevOps Project" \
                        -Dsonar.sources=backend/src/main/java,frontend/src \
                        -Dsonar.java.binaries=backend/target/classes
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Trivy File System Scan') {
            steps {
                sh 'trivy fs . --format table -o trivy-fs-report.html'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t $BACKEND_IMAGE ./backend'
                sh 'docker build -t $FRONTEND_IMAGE ./frontend'
            }
        }

        stage('Trivy Docker Image Scan') {
            steps {
                sh 'trivy image $BACKEND_IMAGE --format table -o trivy-backend-image-report.html'
                sh 'trivy image $FRONTEND_IMAGE --format table -o trivy-frontend-image-report.html'
            }
        }

        stage('DockerHub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Images to DockerHub') {
            steps {
                sh 'docker push $BACKEND_IMAGE'
                sh 'docker push $FRONTEND_IMAGE'
            }
        }
    }
        stage('Deploy to Kubernetes') {
    steps {

        sh 'kubectl apply -f kubernetes/namespace.yaml'

        sh 'kubectl apply -f kubernetes/postgres-secret.yaml'
        sh 'kubectl apply -f kubernetes/postgres-configmap.yaml'
        sh 'kubectl apply -f kubernetes/postgres-pvc.yaml'
        sh 'kubectl apply -f kubernetes/postgres-deployment.yaml'
        sh 'kubectl apply -f kubernetes/postgres-service.yaml'

        sh 'kubectl apply -f kubernetes/backend-deployment.yaml'
        sh 'kubectl apply -f kubernetes/backend-service.yaml'

        sh 'kubectl apply -f kubernetes/frontend-deployment.yaml'
        sh 'kubectl apply -f kubernetes/frontend-service.yaml'

        sh 'kubectl apply -f kubernetes/ingress.yaml'
    }
}
    post {
        always {
            archiveArtifacts artifacts: 'trivy-*.html', allowEmptyArchive: true
        }
    }
}
