pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('backend') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                        sonar-scanner \
                        -Dsonar.projectKey=chai-kafe-devops \
                        -Dsonar.projectName="Chai Kafe DevOps Project" \
                        -Dsonar.sources=backend/src/main/java,frontend/src \
                        -Dsonar.java.binaries=backend/target/classes
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Trivy File System Scan') {
            steps {
                sh 'trivy fs . --format table -o trivy-fs-report.html'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t chai-kafe-backend:latest ./backend'
                sh 'docker build -t chai-kafe-frontend:latest ./frontend'
            }
        }

        stage('Trivy Docker Image Scan') {
            steps {
                sh 'trivy image chai-kafe-backend:latest --format table -o trivy-backend-image-report.html'
                sh 'trivy image chai-kafe-frontend:latest --format table -o trivy-frontend-image-report.html'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'trivy-*.html', allowEmptyArchive: true
        }
    }
}
