apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chai-kafe
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
